{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-practice.serviceAccountName" . }}
  labels:
    {{- include "devops-practice.labels" . | nindent 4 }}
{{- end }}
